mShop/urls.py
from django.conf.urls.static import static
from mShop import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("shop.urls")),
]
urlpatterns += static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"
urlpatterns = [
    path("", views.index, name="index"),
    path("datails/<int:p_id>/", views.details, name="detail"),
    path("cart/", views.cart, name="cart"),
    path("show_cart/", views.show_cart, name="show_cart"),
    path("get_date/", views.get_date, name="get_date"),
]

shop/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model


class Category(models.Model):
    name: models.CharField = models.CharField(max_length=300)

    def __str__(self):
        return self.name


class Product(models.Model):
    name: models.CharField = models.CharField(max_length=300)
    price: models.IntegerField = models.IntegerField()
    description: models.CharField = models.CharField(max_length=1000)
    category: models.ForeignKey = models.ForeignKey(Category, on_delete=models.CASCADE)
    picture: models.ImageField = models.ImageField(null=True)

    def __str__(self):
        return self.id


User = get_user_model()


class ShoppingCart(models.Model):
    product: models.ManyToManyField = models.ManyToManyField(Product)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.product


class Detail(models.Model):
    product: models.OneToOneField = models.OneToOneField(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.product

shop/views/cart.py
from .imports import *


@csrf_exempt
def cart(request):
    selected_product = get_object_or_404(Product, id=request.POST['cart'])
    cookie = ""
    if "product" in request.COOKIES:
        cookie += request.COOKIES["product"] + "_"
    cookie += str(selected_product.id)
    # setting the cookies
    response = redirect("shop:show_cart")
    response.set_cookie("product", cookie)
    try:
        print(request.POST['cart'])
    except (Exception, TypeError):
        print("kir shodi!")
    return response

shop/views/detail.py
from .imports import *


def details(request, p_id):
    context = {"product": Product.objects.get(id=p_id)}
    return render(request, "shop/shop/details.html", context)

shop/views/get_date.py
from .imports import *


@csrf_exempt
def get_date(request):
    response = HttpResponse(request.COOKIES["product"])
    return response

shop/views/imports.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, HttpResponse, get_object_or_404, HttpResponseRedirect, redirect
from django.urls import reverse
from shop.models import *

shop/views/index.py
from .imports import *


def index(request):
    context = {"product": Product.objects.all()}
    return render(request, "shop/index.html", context)

shop/views/show_cart.py
from .imports import *


@csrf_exempt
def show_cart(request):
    product_names = []
    cookies = request.COOKIES["product"]
    cookies = cookies.split("_")
    for item in cookies:
        product_names.append(item)
    product_list = []
    for item in product_names:
        product_list.append(Product.objects.get(id=item))
    context = {
        "products": product_list,
        "user": request.user,
    }
    return render(request, "shop/shop/show_cart.html", context)

templates/shop/base.html
<!DOCTYPE html>{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <title>{% block title %}{% endblock %}</title>
    <!-- MDB icon -->
    {#    <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon"/>#}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"/>
    <!-- Google Fonts Roboto -->
    <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <!-- MDB -->
    <link rel="stylesheet" href="{% static "css/mdb.dark.min.css" %}">
    {% block css %}{% endblock %}
</head>
<body>
<!-- Start your project here-->
{% include "shop/menu.html" %}
{% block body %}{% endblock %}

<!-- End your project here-->

<!-- MDB -->
<script type="text/javascript" src="{% static "js/mdb.min.js" %}"></script>

<!-- Custom scripts -->
<script type="text/javascript"></script>
{% block js %}{% endblock %}
</body>
</html>

templates/shop/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cart</title>
    <link rel="stylesheet" href="../../static/css/mdb.dark.min.css">
    <link rel="stylesheet" href="../../static/shop/css/index.css">
</head>
<body>
<div class="container">
    <h3>
        Hello you are in shopping cart {{ user }}!<br/><br/>
    </h3>
    <h4>
        your cart:<br/><br/>
    </h4>
    {#    product list#}
    {% if products %}
        {% for p in products %}
            <img class="img-thumbnail" src="{{ p.picture.url }}" alt="picture"><br/><br/>
            name: {{ p }}<br/><br/>
            price: {{ p.price }}<br/><br/>
            category: {{ p.category }}<br/><br/>
            <hr/>
        {% endfor %}
    {% endif %}

    {#    single product#}
    {% if product %}
        <img class="img-thumbnail small" src="{{ product.picture.url }}" alt="picture"><br/><br/>
        name: {{ product }}<br/><br/>
        price: {{ product.price }}<br/><br/>
        category: {{ product.category }}<br/><br/>
        <hr/>
    {% endif %}
    <a href="{% url "shop:index" %}">
        <input class="btn btn-success btn-rounded btn-dark" type="button" value="continue shopping">
    </a><br/><br/>
</div>
</body>
</html>

templates/shop/index.html
{% extends "shop/base.html" %}{% load static %}
{% block title %}Home{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static "shop/css/index.css" %}">
{% endblock %}
{% block js %}{% endblock %}
{% block body %}
    {% for p in product %}
        <div>
            {{ forloop.counter }}
            {% if p.picture %}
                <img class="avatar" src="{{ p.picture.url }}" alt="img">
            {% endif %}
            <a href="{% url "shop:detail" p.id %}">Name = {{ p.name }}</a>
            price = {{ p.price }}
        </div>
    {% endfor %}
{% endblock %}

templates/shop/menu.html
<a href="/">home</a>

templates/shop/shop/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cart</title>
    <link rel="stylesheet" href="../../../static/css/mdb.dark.min.css">
    <link rel="stylesheet" href="../../../static/shop/css/index.css">
</head>
<body>
<div class="container">
    <h3>
        Hello you are in shopping cart {{ user }}!<br/><br/>
    </h3>
    <h4>
        your cart:<br/><br/>
    </h4>
    {#    product list#}
    {% if products %}
        {% for p in products %}
            <img class="img-thumbnail" src="{{ p.picture.url }}" alt="picture"><br/><br/>
            name: {{ p }}<br/><br/>
            price: {{ p.price }}<br/><br/>
            category: {{ p.category }}<br/><br/>
            <hr/>
        {% endfor %}
    {% endif %}

    {#    single product#}
    {% if product %}
        <img class="img-thumbnail small" src="{{ product.picture.url }}" alt="picture"><br/><br/>
        name: {{ product }}<br/><br/>
        price: {{ product.price }}<br/><br/>
        category: {{ product.category }}<br/><br/>
        <hr/>
    {% endif %}
    <a href="{% url "shop:index" %}">
        <input class="btn btn-success btn-rounded btn-dark" type="button" value="continue shopping">
    </a><br/><br/>
</div>
</body>
</html>

templates/shop/shop/details.html
{% extends "shop/base.html" %}{% load static %}
{% block title %}Detail page{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static "css/mdb.dark.min.css" %}">
    <link rel="stylesheet" href="{% static "shop/css/index.css" %}">
{% endblock %}
{% block js %}
    <script src="{% static "shop/js/jquery.min.js" %}"></script>
    <script src="{% static "shop/js/index.js" %}"></script>
{% endblock %}
{% block body %}
    <div class="container">
        {% if product.picture %}
            <img class="avatar" src="{{ product.picture.url }}" alt="image">
        {% endif %} <br/>
        <p id="name">name: {{ product.name }} <br/></p>
        <p id="price">price: {{ product.price }} toman<br/></p>
        <p id="category">category: {{ product.category }} <br/></p>
        <form id="form" action="{% url "shop:cart" %}" method="post">
            {% csrf_token %}
            <fieldset>
                <input type="hidden" name="cart" id="id" value="{{ product.id }}">
            </fieldset>
            <input class="btn btn-success btn-rounded btn-dark" type="submit" value="add to cart">
        </form>
    </div>
{% endblock %}
bro to js

templates/shop/shop/show_cart.html
{% extends "shop/base.html" %}{% load static %}
{% block title %}Cart page{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static "css/mdb.dark.min.css" %}">
    <link rel="stylesheet" href="{% static "shop/css/index.css" %}">
{% endblock %}

{% block body %}
    <div class="container">
        <h3>
            Hello you are in shopping cart {{ user }}!<br/><br/>
        </h3>
        <h4>
            your cart:<br/><br/>
        </h4>
        {#    product list#}
        {% if products %}
            {% for p in products %}
                <img id="product_img" class="img-thumbnail" src="{{ p.picture.url }}" alt="picture">
                name: {{ p.name }}<br/><br/>
                price: {{ p.price }}<br/><br/>
                category: {{ p.category }}<br/><br/>
                <hr/>
            {% endfor %}
        {% endif %}
        <input id="check" type="button" class="btn btn-success btn-rounded btn-dark" value="check cart">
        <a href="{% url "shop:index" %}">
            <input class="btn btn-success btn-rounded btn-dark" type="button" value="continue shopping">
        </a><br/><br/>
    </div>

{% endblock %}
{% block js %}
    <script src="{% static "shop/js/jquery.min.js" %}"></script>
    <script src="{% static "shop/js/index.js" %}"></script>
{% endblock %}

templates/shop/show_cart.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Show_Cart</title>
    <link rel="stylesheet" href="{% static "css/mdb.dark.min.css" %}">
    <link rel="stylesheet" href="{% static "shop/css/index.css" %}">
</head>
<body>
<div class="container">
    <h3>
        Hello you are in shopping cart {{ user }}!<br/><br/>
    </h3>
    <h4>
        your cart:<br/><br/>
    </h4>
    {#    product list#}
    {% if products %}
        {% for p in products %}
            <img id="product_img" class="img-thumbnail" src="{{ p.picture.url }}" alt="picture">
            name: {{ p.name }}<br/><br/>
            price: {{ p.price }}<br/><br/>
            category: {{ p.category }}<br/><br/>
            <hr/>
        {% endfor %}
    {% endif %}
    <input id="check" type="button" class="btn btn-success btn-rounded btn-dark" value="check cart">
    <a href="{% url "shop:index" %}">
        <input class="btn btn-success btn-rounded btn-dark" type="button" value="continue shopping">
    </a><br/><br/>
</div>
<script src="{% static "shop/js/jquery.min.js" %}"></script>
<script src="{% static "shop/js/index.js" %}"></script>
</body>
</html>